- .gitignore
- README.md
- lib/saml_authenticator.rb
- spec/saml_authenticator_spec.rb
This PR adds two new settings:
- `DISCOURSE_SAML_DEFAULT_EMAILS_VALID`
- `DISCOURSE_SAML_VALIDATE_EMAIL_FIELDS`
By default `email_valid` is true, this behaviour can be changed by setting `DISCOURSE_SAML_DEFAULT_EMAILS_VALID` to "false".
`DISCOURSE_SAML_VALIDATE_EMAIL_FIELDS` accepts pipe separated group names that are supplied in `memberOf` attribute in SAML payload. If the group name specified in the value matches that from `memberOf` attribute than the `email_valid` is set to `true`, otherwise it defaults to `false`. This setting overrides `DISCOURSE_SAML_DEFAULT_EMAILS_VALID`.
> FEATURE: two new settings for email_valid defaults

- lib/saml_authenticator.rb
The name of the attribute that contains the user's groups should be changeable.
Ipsilon IdP for example uses just 'groups', and that is hardcoded.
Please advise if parameter name is sensible/conforming to your standards.
> Allow changing of the groups attribute name

- plugin.rb
See https://meta.discourse.org/t/auth-provider-plugin-information-for-plugin-authors/102392
Prevents this message from being logged
```
Deprecation notice: background_color is no longer functional. Please use CSS instead 
At /var/www/discourse/lib/plugin/instance.rb:527:in `block (2 levels) in auth_provider`
```
> background_color has been deprecated

- lib/saml_authenticator.rb
- plugin.rb
I was finally able to make the changes as suggested [here](https://github.com/discourse/discourse-saml/pull/19). 
This change allows overriding the base URL with a GlobalSetting called saml_base_url.
> Support for overriding base_url using saml_base_url GlobalSetting (take 2)

- lib/saml_authenticator.rb
- spec/saml_authenticator_spec.rb
In case the user isn't assigned to any (non-automatic) group, the user
wasn't added.
> Fix adding user to his first group

- README.md
- lib/saml_authenticator.rb
I've added two settings that Ruby SAML processes when creating or answering a logout request:
- `logout_requests_signed`: [defaults to false](https://github.com/onelogin/ruby-saml/blob/63f43a7f9b830dfd690457a78a78fac48359944f/lib/onelogin/ruby-saml/settings.rb#L233)
- `logout_responses_signed`: [defaults to false](https://github.com/onelogin/ruby-saml/blob/63f43a7f9b830dfd690457a78a78fac48359944f/lib/onelogin/ruby-saml/settings.rb#L234)
https://github.com/onelogin/ruby-saml#signing
We need them for integration with our idp that expects service providers to sign all requests and responses.
> FEATURE: Add settings for signing logout requests and responses

- lib/saml_authenticator.rb
- spec/saml_authenticator_spec.rb
Now we can sync or create user fields based on the new `saml_user_field_statements` environment variable's mapping.
> FEATURE: sync user fields as per `saml_user_field_statements` env variable.

- plugin.rb
We started seeing [this error](https://github.com/onelogin/ruby-saml/issues/577) on some of our sites. It was fixed by 1.12.1.
> DEV: Bump ruby-saml version from 1.7.2 to 1.13.0

- plugin.rb
Our hosted sites running in stable branch have issues with `rexml` gem and returning "missing gem" error. This gem is required by 'ruby-saml v1.13.0' gem.
> DEV: explicitly require `rexml` gem in the plugin file.

- lib/saml_authenticator.rb
- spec/saml_authenticator_spec.rb
For `name`, the previous intention was to use the `fullName` attribute, and then fallback to "firstname lastname". However, a bug in the implementation meant that the `fullName` was skipped.
This commit updates the logic to lean on omniauth-saml's attribute_statements for the fullName, firstName and lastName attributes, and also updates the priority logic so that fullName is indeed prioritized.
> FIX: Update name selection logic

- lib/discourse_saml/saml_omniauth_strategy.rb
- lib/saml_authenticator.rb
- plugin.rb
- spec/integration/saml_post_mode_spec.rb
Putting this logic into the omniauth strategy is much cleaner because:
- we no longer need a Rails controller and the associated `custom_url` parameter
- we can re-use the `authn_request` instance which is automatically generated by the omniauth strategy, rather than re-implementing that logic
- the behavior is decided at runtime, rather than during initialization. This makes it testable, and is another step on the way to making the plugin multisite-compatible
This commit also introduces a spec for the feature.
> DEV: Move `saml_request_method` handling into the OmniAuth strategy

- config/locales/client.en.yml
- plugin.rb
This means that the name/title can be set per-site and per-locale. This change is backwards-compatible - any existing sites which have configured the GlobalSettings will use those cluster-wide.
> DEV: Fallback to locale strings for name/title

- lib/saml_authenticator.rb
- plugin.rb
- spec/integration/saml_forced_domains_spec.rb
This centralises our logic for accessing settings. This particular commit should be a no-op. I intend to followup with the new site setting definitions in a future commit.
> DEV: Use a helper method for all settings, and prefer SiteSettings

- lib/saml_authenticator.rb
The prefix is added by the helper. Adding it here causes it to be prefixed twice.
> FIX: Remove prefix from base_url

- lib/discourse_saml/saml_omniauth_strategy.rb
- spec/integration/saml_cross_site_spec.rb
SAML flows end in a cross-site POST back to Discourse. We have the SameSite=lax attributes on our session cookies so this cross-site POST request has no cookies, and therefore we are unable to check any values in the `session`.
This commit makes the browser re-submit the POST request in a SameSite context (i.e. with cookies). Upon receiving a cross-site POST, it renders a simple HTML form with some auto-submit JS. This form submits exactly the same data to the same URL, but this time the request will include the cookies, and authentication can complete properly
> FIX: Ensure SAML follows after-login redirects

- lib/discourse_saml/saml_omniauth_strategy.rb
- spec/integration/saml_cross_site_spec.rb
Follow-up to d137e9814140f2bfa1ef1021bd0fb8b891378570. If the cross-site POST returns a Set-Cookie header, it will overwrite the existing session, and we'll lose the redirect URL. This commit instructs rack not to persist a session cookie in this response.
> FIX: Do not override existing session cookie during callback

- config/locales/client.en.yml
- config/locales/server.en.yml
- config/settings.yml
- lib/saml_authenticator.rb
- plugin.rb
- spec/integration/saml_forced_domains_spec.rb
- spec/integration/saml_post_mode_spec.rb
- spec/integration/saml_single_log_out_spec.rb
- spec/saml_authenticator_spec.rb
GlobalSettings configured via environment variables will continue to take precendence, so this change is backwards compatible.
- `.presence` is added to string values, since 'unset' site settings are never `nil`
- saml_force_domains is split on `|` and `,` because site settings expect a `|`, while the old global setting expected a `,`
> FEATURE: Allow the plugin to be configured using site settings

- lib/saml_authenticator.rb
- spec/saml_authenticator_spec.rb
Regression introduced in e9f9150b
> FIX: Ignore empty `saml_base_url` site setting

- lib/saml_authenticator.rb
- spec/integration/saml_staged_user_handling_spec.rb
Core takes care of suggesting usernames during normal signup. Suggesting them here as well can cause unexpected issues (e.g. when staged users sign up).
The SAML plugin currently has a bespoke `auto_create_account` implementation, which **does** need to do its own username suggestion. Therefore this commit moves all the suggestion logic into `auto_create_account`.
An integration spec for staged-user signup is also introduced.
(integration spec also requires https://github.com/discourse/discourse/pull/15259 in order to pass)
> FIX: Defer UsernameSuggester logic to the auto_create_account

- lib/saml_authenticator.rb
- spec/saml_authenticator_spec.rb
Some variable renames were missed, and some specs are no longer relevant
> FIX: Correct after_create_account errors from 4e0a5e0a

- lib/discourse_saml/saml_omniauth_strategy.rb
The SAML spec requires compression for the standard Redirect binding. However, it is not used in the POST binding. This regressed during the refactoring of 95ccea3f
> FIX: Do not compress SAML request for POST binding

- lib/discourse_saml/saml_omniauth_strategy.rb
- spec/integration/saml_post_mode_spec.rb
In the vast majority of cases, this wasn't causing a problem because browsers will auto-detect the content-type. However, if any intermediate proxies add the `X-Content-Type-Options: nosniff` header, then the html will be displayed as plain text, and login will be broken.
> FIX: Add `content-type` header to auto-submitting form

- lib/discourse_saml/saml_omniauth_strategy.rb
- spec/integration/saml_post_mode_spec.rb
The change in 245b70d4 means that the CSP middleware now activates for the `/auth/saml` route. That's good, but it also broke things for subfolder installations because the CSP includes the base_path, while the SAML JS script url did not. This commit fixes that, and adds an integration spec to ensure the script is included in the script_src directive for regular and subfolder sites.
> FIX: Ensure JS script path is correct for subfolder

- config/locales/server.en.yml
- lib/saml_authenticator.rb
- spec/integration/saml_sync_attributes_spec.rb
- spec/saml_authenticator_spec.rb
Requires https://github.com/discourse/discourse/pull/15378
> DEV: Re-use core email and username overriding logic

- db/migrate/20211230141200_migrate_saml_user_info.rb
- lib/saml_authenticator.rb
- plugin.rb
- spec/integration/saml_staged_user_handling_spec.rb
- spec/integration/saml_sync_attributes_spec.rb
- spec/saml_authenticator_spec.rb
All data will be automatically migrated from `oauth2_user_infos` to the `user_associated_accounts` table
> DEV: Migrate plugin to ManagedAuthenticator and UserAssociatedAccount

- lib/saml_authenticator.rb
- spec/saml_authenticator_spec.rb
In production, the SAML omniauth strategy returns some very complex data structures in the `extra` data. These have circular references, and can cause a "stack level too deep" error when serializing to JSON for the UserAssociatedAccount model. This commit simplifies thing so we only try to store the attributes hash.
> FIX: Simplify data to store in `extra` column

- plugin.rb
`name` is nil... so this logic was not working at all
> FIX: Hide settings if configured via environment variables

- lib/saml_authenticator.rb
And add a option to include multiple certificates in site setting with "|" separator.
> DEV: include original certificate in `idp_cert_multi` variable.

- lib/discourse_saml/saml_omniauth_strategy.rb
- spec/integration/saml_post_mode_spec.rb
Uses https://github.com/discourse/discourse/pull/26052, but falls back to the old behavior if that method is not present
> DEV: Add support for core content_security_policy_strict_dynamic

- lib/saml_authenticator.rb
- spec/saml_authenticator_spec.rb
Previously, since we didn't call 'refresh_automatic_groups' after when a user become admin/mod they didn't added to the group automatically.
> FEATURE: add to staff group when user become admin via sync

- plugin.rb
Core already includes rexml and including it here makes updating the gem more difficult.
> DEV: Remove direct rexml requirement

- README.md
Copied better documentation of variables from here https://github.com/discourse/discourse-saml/blob/main/config/locales/server.en.yml
This makes it easier setting up SAML authentification with github.
> Better documentation for Certificate configuration

- spec/fabricators/saml_user_info.rb
- spec/saml_authenticator_spec.rb
While adding a new feature regarding "group sync", _many_ updates were made to the `saml_authenticator_spec`.
This PR contains those spec updates standalone so the following "group sync" PR would be more focused on the feature.
- move away from instance variables (`@user`, `@authenticator`...)
- ruby hash shorthand (`info: { name:, email: email }`)
- no more group positional arrays 😣  (`group_names[0..1]` -> `[group1.name, group2.name]`)
> DEV: Move tests away from instance variables and favour fab

- README.md
- config/settings.yml
- lib/saml_authenticator.rb
- spec/saml_authenticator_spec.rb
This PR 
- :one: extends the `saml_groups_attribute` to accept an array of attributes, and 
- :two: adds a new setting: `saml_groups_use_full_name`.
- :three: it ensures the group sync feature removes the groups from the old attributes if it exists
:one: 
Previously, we only allow usage of one attribute e.g. `SiteSetting.saml_groups_attribute="memberOf"`. This PR adds support for multiple attributes.
Assuming the following attributes in raw_info:
```
#<UserAssociatedAccount:
provider_name: "saml",
extra: {
"raw_info"=> {
"Name"=>["Tay, Steak"],
"Email"=>["steak@tay.com"],
"Country"=>["Singapore"],
"Location"=>["Changi","Orchard"], 
"memberOf"=>["Cats", "Animals"], 
}
}
```
With existing `SiteSetting.saml_groups_attribute="memberOf"` we would add Steak to 2 groups 
``` …
```
> FEATURE: Allow multiple attributes for group sync and also using group full_name

- lib/saml_authenticator.rb
rename idp_sxo_target_url vars to idp_sxo_service_url according to upstream ruby-saml
this prevented SLO from working*. SSO works because of #44 which is probably why it wasn't caught yet
*threw HTTP 501 - Not Implemented
> FIX: replace idp_sxo_target_url with idp_sxo_service_url

- config/locales/server.en.yml
- config/settings.yml
- lib/discourse_saml/saml_omniauth_strategy.rb
- lib/saml_authenticator.rb
- spec/lib/saml_omniauth_strategy_spec.rb
- spec/saml_authenticator_spec.rb
This adds site settings to enable/disable users from manually connecting and revoking SAML associated accounts, and also fixes a couple issues I found while connecting a SAML account to an existing user.
First, [omniauth-saml](https://github.com/omniauth/omniauth-saml) adds a field `response_object` to the `extra` part of the auth hash, containing the entire `OneLogin::RubySaml::Response` object data. 
When reconnect=true, OmniauthCallbacksController serializes the auth hash into JSON to save it in the session, so it can be recreated after reconnecting the user. I was seeing a **SystemStackError** during the `to_json` call on the auth hash trying to serialize the field `extra[:response_object][:document]` (It's an XMLSecurity::SignedDocument that resolves to the string "<UNDEFINED> ... …
> Fix reconnect path so users can manually connect a SAML account

- config/settings.yml
- plugin.rb
Allows admins to set up an alternative to the "user" icon, displayed on the login/signup screen buttons and the associated accounts section in user preferences.
> DEV: Add setting for icon on SAML login button and associated accounts table
